
const CLUB_MEMBER_SELECT = "CLUB_MEMBER_SELECT";
const CLUB_MEMBER_SELECT_EMPTY = "CLUB_MEMBER_SELECT_EMPTY";
const CLUB_MEMBER_SELECT_ERROR = "CLUB_MEMBER_SELECT_ERROR";
const CLUB_MEMBER_SELECT_DATA = "CLUB_MEMBER_SELECT_DATA"
const CLUB_MEMBER_SELECT_DATA2 = "CLUB_MEMBER_SELECT_DATA2"
const CLUB_MEMBER_SELECT_RESET = "CLUB_MEMBER_SELECT_RESET"

/*-------------------------------alert-----------------------------*/
const ALERT = "ALERT";

/*-------------------------------LOGIN-----------------------------*/
const LOGIN_V1_TYPE = "LOGIN_V1_TYPE";
const LOGIN_V1_loading = "LOGIN_V1_loading";
const LOGIN_V1_TYPE_error = "LOGIN_V1_TYPE_error";
const LOGIN_V1_TYPE_SUCCESS = "LOGIN_V1_TYPE_SUCCESS";
/*-------------------------------*/

/*-------------------------------difination-----------------------------*/
const REGISTRATION_COURSE_V1_SELECT = "REGISTRATION_COURSE_V1_SELECT";
const REGISTRATION_COURSE_V1_SELECT_MORE = "REGISTRATION_COURSE_V1_SELECT_MORE";
const REGISTRATION_COURSE_V1_INSERT = "REGISTRATION_COURSE_V1_INSERT";
const REGISTRATION_COURSE_V1_EMPTY = "REGISTRATION_COURSE_V1_EMPTY";
const REGISTRATION_COURSE_V1_LIST = "REGISTRATION_COURSE_V1_LIST";

const FEEDBACK_V1_UPDATE = "FEEDBACK_V1_UPDATE";
const FEEDBACK_V1_SELECT = "FEEDBACK_V1_SELECT";
const FEEDBACK_V1_SELECT_SUBMITTED = "FEEDBACK_V1_SELECT_SUBMITTED"

const FAQ_V1_SELECT = "FAQ_V1_SELECT";
const FAQ_V1_INSERT = "FAQ_V1_INSERT";
const FAQ_V1_EDIT = "FAQ_V1_EDIT";
const FAQ_V1_DELETE = "FAQ_V1_DELETE";

const PISHKHAN_V1_SELECT = "PISHKHAN_V1_SELECT";

const BRANCHES_V1_SELECT = "BRANCHES_V1_SELECT";

const SLIDER_V1_SELECT = "SLIDER_V1_SELECT";

const SELECT_IPO_LIST = "SELECT_IPO_LIST";
const SELECT_USER_STATUS = "SELECT_USER_STATUS";
const SELECT_USER_STATUS_EMPTY = "SELECT_USER_STATUS_EMPTY"
const SELECT_IPO_LIST_TITLE = "SELECT_IPO_LIST_TITLE";

const SELECT_IPOLIST_EXCEL = "SELECT_IPOLIST_EXCEL";

const SELECT_IPO_LIST_EMPTY = "SELECT_IPO_LIST_EMPTY";

/*-------------------------------*/

/*-------------------------------ERRORS-----------------------------*/
const ERROR_RALERT = "ERRO_RALERT";
const ERROR_CLOSE = "ERROR_CLOSE";
const ERROR405 = "ERROR405";
/*-------------------------------*/

/*------------------------------- STATIC ACCOUNTS-----------------------------*/
const EDUCATION_VIDEO_V1_SELECT = "EDUCATION_VIDEO_V1_SELECT";

const ACCOUNTS_V1_SELECT = "ACCOUNTS_V1_SELECT";
const ACCOUNTS_V1_EDIT_INSERT_DELETE = "ACCOUNTS_V1_EDIT_INSERT_DELETE";
const JOBSOPPORTUNITIES_V1_SELECT = "JOBSOPPORTUNITIES_V1_SELECT";

const TELEGRAM_LINK_V1_SELECT = "TELEGRAM_LINK_V1_SELECT";
const TELEGRAM_LINK_V1_UPDATE = "TELEGRAM_LINK_V1_UPDATE";

const SYSTEMS_V1_SELECT = "SYSTEMS_V1_SELECT";
const SYSTEMS_V1_UPDATE = "SYSTEMS_V1_UPDATE";

const ABOUT_US_V1_SELECT = "ABOUT_US_V1_SELECT";
const CREADIT_V1_SELECT = "CREADIT_V1_SELECT";
/*-------------------------------*/
const REGISTRATION_GUIDE_V1_SELECT = "REGISTRATION_GUIDE_V1_SELECT";
const REGISTRATION_GUIDE_V1_UPDATE = "REGISTRATION_GUIDE_V1_UPDATE";

const EDUCATION_SOFTWARE_V1_SELECT = "EDUCATION_SOFTWARE_V1_SELECT";
const EDUCATION_SOFTWARE_V1_UPDATE = "EDUCATION_SOFTWARE_V1_UPDATE";

const BROCHURES_V1_SELECT = "BROCHURES_V1_SELECT";
const IPO_V1_SELECT = "IPO_V1_SELECT";
/*-------------------------------*/

/*------------------------------------------------- */

/*--------------POST-FORUM-----------------*/
const FORUM_V1_SELECT = "FORUM_V1_SELECT";
const POST_NOTAPPROVE_V1_SELECT = "POST_NOTAPPROVE_V1_SELECT";
const POST_NOTAPPROVE_V1_SELECT_MORE = "POST_NOTAPPROVE_V1_SELECT_MORE";
const POST_APPROVE_V1_SELECT = "POST_APPROVE_V1_SELECT";
const POST_APPROVE_V1_SELECT_MORE = "POST_APPROVE_V1_SELECT_MORE";
const POST_NOTVISIBLE_V1_SELECT = "POST_NOTVISIBLE_V1_SELECT";
const POST_NOTVISIBLE_V1_SELECT_MORE = "POST_NOTVISIBLE_V1_SELECT_MORE";
const POST_V1_SELECT_EMPTY = "POST_V1_SELECT_EMPTY";

const POST_V1_SELECT_FILTER = "POST_V1_SELECT_FILTER";
const POST_V1_SELECT_MORE_FILTER = "POST_V1_SELECT_MORE_FILTER";

const POST_V1_SELECT = "POST_V1_SELECT";
const COMMENTS_V1_SELECT = "COMMENTS_V1_SELECT";
const COMMENTS_V1_EMPTY = "COMMENTS_V1_EMPTY";
const POST_V1_INFORMATIN = "POST_V1_INFORMATIN";
const POST_V1_INFORMATIN_EMPTY = "POST_V1_INFORMATIN_EMPTY";
/*-------------------------------*/

/*--------------profile----------------*/
const STCOK_V1_SELECT = "STCOK_V1_SELECT";
const STOCK_CASH_SELECT = "STOCK_CASH_SELECT";
const STOCK_CASH_SELECT_LOADING = "STOCK_CASH_SELECT_LOADING";
const STCOK_V1_SELECT_EMPTY = "STCOK_V1_SELECT_EMPTY";
const PROFILE_V1_SELECT = "PROFILE_V1_SELECT";
const PROFILE_V1_SELECT_EMPTY = "PROFILE_V1_SELECT_EMPTY";

const ORDERS_V1_SELECT = "ORDERS_V1_SELECT";
const ORDERS_V1_SELECT_AGGREGATES = "ORDERS_V1_SELECT_AGGREGATES";
const ORDERS_V1_SELECT_MORE = "ORDERS_V1_SELECT_MORE";
const PROFILE_V1_EMPTY = "PROFILE_V1_EMPTY";
const PROFILE_V1_SELECT_ORDER = "PROFILE_V1_SELECT_ORDER";
const PERSON_V1_SELECT_INTEGRATE_PROFILES = "PERSON_V1_SELECT_INTEGRATE_PROFILES";
const PERSON_V1_SELECT_INTEGRATE_PROFILES_EMPTY = "PERSON_V1_SELECT_INTEGRATE_PROFILES_EMPTY";

const STOCK_V1_SELECT_SUMMARIES = "STOCK_V1_SELECT_SUMMARIES";
const STOCK_V1_SELECT_SEARCHSYMBOL = "STOCK_V1_SELECT_SEARCHSYMBOL";
const STOCK_V1_SELECT_SUMMARIES_MORE = "STOCK_V1_SELECT_SUMMARIES_MORE";
const STOCK_V1_SELECT_SUMMARIES_PAGE_STOCK_EMPTY = "STOCK_V1_SELECT_SUMMARIES_PAGE_STOCK_EMPTY";
const STOCK_V1_SELECT_SUMMARIES_PAGE_STOCK = "STOCK_V1_SELECT_SUMMARIES_PAGE_STOCK";

const STOCK_V1_MANAGEMENT_DATA_SELECT = "STOCK_V1_MANAGEMENT_DATA_SELECT";
const SECTOR_V1_MANAGEMENT_DATA_SELECT = "SECTOR_V1_MANAGEMENT_DATA_SELECT";

const PROFILE_V1_SELECT_INTRODUCING = "PROFILE_V1_SELECT_INTRODUCING";

const CREADIT_PROFILE_V1_SELECT = "CREADIT_PROFILE_V1_SELECT";
const CREADIT_PROFILE_V1_EMPTY = "CREADIT_PROFILE_V1_EMPTY";
/*-------------------------------*/

const COURSES_V1_SELECT = "COURSES_V1_SELECT";
const COURSES_V1_EMPTY = "COURSES_V1_EMPTY";
const COURSES_V1_INSERT = "COURSES_V1_INSERT";

const GIFT_V1_SELECT_REGISTRATIONS = "GIFT_V1_SELECT_REGISTRATIONS";
const GIFT_V1_SELECT_REGISTRATIONS_RESULT_ACTION = "GIFT_V1_SELECT_REGISTRATIONS_RESULT_ACTION";
const GIFT_V1_SELECT_REGISTRATIONS_RESULT_ACTION_EMPTY = "GIFT_V1_SELECT_REGISTRATIONS_RESULT_ACTION_EMPTY";
const GIFT_V1_SELECT_REGISTRATIONS_EMPTY = "GIFT_V1_SELECT_REGISTRATIONS_EMPTY";
const GIFT_V1_SELECT_REGISTRATIONS_EXCEL = "GIFT_V1_SELECT_REGISTRATIONS_EXCEL";
const GIFT_V1_SELECT_REGISTRATIONS_EXCEL_EMPTY = "GIFT_V1_SELECT_REGISTRATIONS_EXCEL_EMPTY";
const GIFT_V1_SELECT_REGISTRATIONS_EXCEL_LOADING = "GIFT_V1_SELECT_REGISTRATIONS_EXCEL_LOADING";
const GIFT_V1_SELECT_REGISTRATIONS_EXCEL_ISOK = "GIFT_V1_SELECT_REGISTRATIONS_EXCEL_ISOK";
const GIFT_V1_SELECT_REGISTRATIONS_MORE = "GIFT_V1_SELECT_REGISTRATIONS_MORE";
const GIFT_V1_SELECT = "GIFT_V1_SELECT";

const GIFTAGGREGATED_V1_SELECT = "GIFTAGGREGATED_V1_SELECT";
const GIFTAGGREGATED_V1_SELECT_FILTER = "GIFTAGGREGATED_V1_SELECT_FILTER";
const GIFTAGGREGATED_V1_EMPTY = "GIFTAGGREGATED_V1_EMPTY";
const GIFTAGGREGATED_V1_lOADING = "GIFTAGGREGATED_V1_lOADING";

const GIFTCASHAGGREGATED_V1_SELECT = "GIFTCASHAGGREGATED_V1_SELECT";
const GIFTCASHAGGREGATED_V1_SELECT_FILTER = "GIFTCASHAGGREGATED_V1_SELECT_FILTER";
const GIFTCASHAGGREGATED_V1_EMPTY = "GIFTCASHAGGREGATED_V1_EMPTY";
const GIFTCASHAGGREGATED_V1_lOADING = "GIFTCASHAGGREGATED_V1_lOADING";



const GIFT_V1_SELECT_MORE = "GIFT_V1_SELECT_MORE";
const GIFT_V1_SELECT_ACTIVE_NAME = "GIFT_V1_SELECT_MORE_ACTIVE_NAME";
const GIFT_V1_EMPTY = "GIFT_V1_EMPTY";
const GIFT_V1_CATEGORIES = "GIFT_V1_CATEGORIES";
const GIFT_V1_SUBCATEGORIES = "GIFT_V1_SUBCATEGORIES";
const GIFTCASH_V1_SELECT = "GIFTCASH_V1_SELECT";


const SUBSCRIPTION_PLANS_V1_SELECT = "SUBSCRIPTION_PLANS_V1_SELECT";
const SIGANL_V1_SELECT = "SIGANL_V1_SELECT";
const SIGANL_V1_DOCUMENT_SELECT = "SIGANL_V1_DOCUMENT_SELECT";
const SIGANL_V1_DOCUMENT_SELECT_EMPTY = "SIGANL_V1_DOCUMENT_SELECT_EMPTY"
const SIGANL_V1_DOCUMENT_SELECT_LOADING = "SIGANL_V1_DOCUMENT_SELECT_LOADING"
const MEMBER_SUBSCRIPTION_V1_SELECT = "MEMBER_SUBSCRIPTION_V1_SELECT";

const DISCOUNT_CODE_SELECT = "DISCOUNT_CODE_SELECT";
const DISCOUNT_CODE_EXCEL_SELECT = "DISCOUNT_CODE_EXCEL_SELECT";
const DISCOUNT_CODE_EXCEL_EMPTY = "DISCOUNT_CODE_EXCEL_EMPTY";

const STEPBYSTEP_DISCOUNT_SELECT = "STEPBYSTEP_DISCOUNT_SELECT";


const BONUS_V1_SELECT = "BONUS_V1_SELECT";
const BONUS_V1_SELECT_REQUESTS = "BONUS_V1_SELECT_REQUESTS";
const BONUS_V1_SELECT_EXCEL = "BONUS_V1_SELECT_EXCEL";
const BONUS_V1_SELECT_EXCEL_REQUEST = "BONUS_V1_SELECT_EXCEL_REQUEST";
const BONUS_V1_SELECT_EXCEL_LOADING = "BONUS_V1_SELECT_EXCEL_LOADING"
const BONUS_V1_SELECT_EXCEL_ISOK = "BONUS_V1_SELECT_EXCEL_ISOK"
const BONUS_V1_SELECT_EXCEL_EMPTY = "BONUS_V1_SELECT_EXCEL_EMPTY"
const BONUS_V1_AGGREGATED = "BONUS_V1_AGGREGATED";
const BONUS_V1_AGGREGATED_LOADING = "BONUS_V1_AGGREGATED_LOADING";

const BONUS_V1_SELECT_MANGEMENT = "BONUS_V1_SELECT_MANGEMENT";
const BONUS_V1_SELECT_MANGEMENT_LOADING = "BONUS_V1_SELECT_MANGEMENT_LOADING";
const BONUS_V1_SELECT_CALCULATE_CONFIICT = "BONUS_V1_SELECT_CALCULATE_CONFIICT";
const BONUS_V1_SELECT_CALCULATE_CONFIICT_LOADING = "BONUS_V1_SELECT_CALCULATE_CONFIICT_LOADING";
const BONUS_V1_SELECT_CALCULATE_CONFIICT_EMPTY = "BONUS_V1_SELECT_CALCULATE_CONFIICT_EMPTY";
const BONUS_V1_SELECT_SELECT_CONFIICT = "BONUS_V1_SELECT_SELECT_CONFIICT";
const BONUS_V1_SELECT_SELECT_CONFIICT_LOADING = "BONUS_V1_SELECT_SELECT_CONFIICT_LOADING";



const COMPETITIONS_V1_SELECT = "COMPETITIONS_V1_SELECT";
const COMPETITIONS_V1_SELECT_IN_RANGE = "COMPETITIONS_V1_SELECT_IN_RANGE";
const PERFORMANCE_SELECT_BY_ID = "PERFORMANCE_SELECT_BY_ID";
const PARTICIPATIONS_V1_SELECT = "PARTICIPATIONS_V1_SELECT";
const PARTICIPATIONS_V1_EMPTY = "PARTICIPATIONS_V1_EMPTY";
const PARTICIPATIONS_ById_V1_EMPTY = "PARTICIPATIONS_ById_V1_EMPTY";
const COMPETITIONS_PROFILE_V1_SELECT = "COMPETITIONS_PROFILE_V1_SELECT";
const COMPETITIONS_PROFILE_V1_EMPTY = "COMPETITIONS_PROFILE_V1_EMPTY";

const NOTIFY_V1_SELECT = "NOTIFY_V1_SELECT";
const NOTIFY_V1_SELECT_MORE = "NOTIFY_V1_SELECT_MORE";
const NOTIFY_V1_SELECT_TOTAL = "NOTIFY_V1_SELECT_TOTAL";
const NOTIFY_V1_SELECT_NATION_ID = "NOTIFY_V1_SELECT_NATION_ID"


const USERS_V1_SELECT = "USERS_V1_SELECT";
const LOG_IN_LIST_SELECT = "LOG_IN_LIST_SELECT";

const CUSTOMERS_V1_SELECT = "CUSTOMERS_V1_SELECT";
const CUSTOMERS_V1_SELECT_LOADING = "CUSTOMERS_V1_SELECT_LOADING";
const CUSTOMER_V1_SELECT_ATTACHMENTS = "CUSTOMER_V1_SELECT_ATTACHMENTS";
const CUSTOMER_V1_SELECT_EMPTY = "CUSTOMER_V1_SELECT_EMPTY";


const EXCEL_GET_DATA = "EXCEL_GET_DATA"
const EXCEL_GET_DATA2 = "EXCEL_GET_DATA2"
const EXCEL_GET_LOADING = "EXCEL_GET_LOADING"
const EXCEL_GET_ISOK = "EXCEL_GET_ISOK"
const EXCEL_GET_EMPTY = "EXCEL_GET_EMPTY"


const SELECT_STOCK_DETAILS = "SELECT_STOCK_DETAILS"
const SELECT_STOCK_DETAILS_EMPTY = "SELECT_STOCK_DETAILS_EMPTY"

/*-------------------------------stock-----------------------------*/
const CHANGE_BROKER_SELECT = "CHANGE_BROKER_SELECT";
const CHANGE_BROKER_SELECT_IMG = "CHANGE_BROKER_SELECT_IMG";
const CHANGE_BROKER_SELECT_EMPTY = "CHANGE_BROKER_SELECT_EMPTY";
const PRTFOLIO_REMAIN = "PRTFOLIO_REMAIN";
const PRTFOLIO_REMAIN_EMPTY = "PRTFOLIO_REMAIN_EMPTY";
const SELECT_INTRODUCTION_DETAIL = "SELECT_INTRODUCTION_DETAIL";
const SELECT_INTRODUCTION_DETAIL_EMPTY = "SELECT_INTRODUCTION_DETAIL_EMPTY";
const UPDATE_CHANGE_INTRODUCER = "UPDATE_CHANGE_INTRODUCER";
const UPDATE_DELETE_INTRODUCER = "UPDATE_DELETE_INTRODUCER"


const SELECT_CLUBMEMBER_COUNT = "SELECT_CLUBMEMBER_COUNT";
const SELECT_TOTAL_BONUS = "SELECT_TOTAL_BONUS";
const SELECT_CLUBMEMBER_REGISTRATION_COUNT = "SELECT_CLUBMEMBER_REGISTRATION_COUNT";
const SELECT_CLUBMEMBER_BY_BOURSE_CODE_COUNT = "SELECT_CLUBMEMBER_BY_BOURSE_CODE_COUNT";
const SELECT_CLUBMEMBER_DAILY_LOGIN_LOG = "SELECT_CLUBMEMBER_DAILY_LOGIN_LOG"


/*----------------------------sejam-------------------------------- */


const GET_KYC_PROFILE_SELECT = "GET_KYC_PROFILE_SELECT"
const GET_KYC_PROFILE_REMOVE = "GET_KYC_PROFILE_REMOVE"



/*----------------------------Marketer-------------------------------- */
const MARKETER_V1_SELECT_LOADING = "MARKETER_V1_SELECT_LOADING"
const MARKETER_V1_SELECT = "MARKETER_V1_SELECT"
const MARKETER_SELECT_ATTACHMENTS = "MARKETER_SELECT_ATTACHMENTS"
const MARKETER_SELECT_ATTACHMENTS_EMPTY = "MARKETER_SELECT_ATTACHMENTS_EMPTY"






const WORK_WITH_US_V1_SELECT = "WORK_WITH_US_V1_SELECT";
const WORK_WITH_US_V1_SELECT_LOADING = "WORK_WITH_US_V1_SELECT_LOADING";
const WORK_WITH_US_V1_SELECT_ATTACHMENTS = "WORK_WITH_US_V1_SELECT_ATTACHMENTS";

const WORK_WITH_US_V1_SELECT_ATTACHMENTS_EMPTY = "WORK_WITH_US_V1_SELECT_ATTACHMENTS_EMPTY";
const WORK_WITH_US_V1_UPDATE = "WORK_WITH_US_V1_UPDATE";


const CONTACT_US_V1_SELECT = "CONTACT_US_V1_SELECT";

const CONTACT_US_V1_SELECT_LOADING = "CONTACT_US_V1_SELECT_LOADING";
const CONTACT_US_V1_SELECT_DETAILS = "CONTACT_US_V1_SELECT_DETAILS";
const CONTACT_US_V1_SELECT_DETAILS_EMPTY = "CONTACT_US_V1_SELECT_DETAILS_EMPTY";


const PAYMENTS_V1_SELECT = "PAYMENTS_V1_SELECT";
const PAYMENTS_V1_SELECT_LOADING = "PAYMENTS_V1_SELECT_LOADING";


export {
  /*-------------------------------EXCEL-----------------------------*/
  EXCEL_GET_DATA,
  EXCEL_GET_DATA2,
  EXCEL_GET_LOADING,
  EXCEL_GET_ISOK,
  EXCEL_GET_EMPTY,

  /*------------------------------------------------------------*/
  CLUB_MEMBER_SELECT,
  CLUB_MEMBER_SELECT_EMPTY,
  CLUB_MEMBER_SELECT_ERROR,
  CLUB_MEMBER_SELECT_DATA,
  CLUB_MEMBER_SELECT_DATA2,
  CLUB_MEMBER_SELECT_RESET,
  /*-------------------------------alert-----------------------------*/
  ALERT,
  /*-------------------------------difination-----------------------------*/
  FEEDBACK_V1_SELECT,
  FEEDBACK_V1_UPDATE,
  FEEDBACK_V1_SELECT_SUBMITTED,
  FAQ_V1_SELECT,
  FAQ_V1_INSERT,
  FAQ_V1_EDIT,
  FAQ_V1_DELETE,
  PISHKHAN_V1_SELECT,
  SLIDER_V1_SELECT,
  SELECT_IPO_LIST,
  SELECT_IPO_LIST_TITLE,
  SELECT_IPOLIST_EXCEL,
  SELECT_IPO_LIST_EMPTY,
  /*-------------------------------LOGIN-----------------------------*/
  LOGIN_V1_TYPE,
  LOGIN_V1_TYPE_SUCCESS,
  LOGIN_V1_loading,
  LOGIN_V1_TYPE_error,
  ERROR405,
  /*-------------------------------*/

  /*-------------------------------ERRORS-----------------------------*/
  ERROR_RALERT,
  ERROR_CLOSE,
  /*-------------------------------*/

  /*------------------------------- STATIC ACCOUNTS-----------------------------*/
  EDUCATION_VIDEO_V1_SELECT,
  ACCOUNTS_V1_SELECT,
  ACCOUNTS_V1_EDIT_INSERT_DELETE,
  JOBSOPPORTUNITIES_V1_SELECT,
  SYSTEMS_V1_SELECT,
  SYSTEMS_V1_UPDATE,
  REGISTRATION_GUIDE_V1_SELECT,
  REGISTRATION_GUIDE_V1_UPDATE,
  TELEGRAM_LINK_V1_SELECT,
  TELEGRAM_LINK_V1_UPDATE,
  ABOUT_US_V1_SELECT,
  CREADIT_V1_SELECT,
  BROCHURES_V1_SELECT,
  IPO_V1_SELECT,
  EDUCATION_SOFTWARE_V1_SELECT,
  EDUCATION_SOFTWARE_V1_UPDATE,
  /*-------------------------------*/

  /*--------------DEFINITIONS-----------------*/
  BRANCHES_V1_SELECT,
  /*------------------------------------------------- */
  REGISTRATION_COURSE_V1_SELECT,
  REGISTRATION_COURSE_V1_SELECT_MORE,
  REGISTRATION_COURSE_V1_INSERT,
  REGISTRATION_COURSE_V1_EMPTY,
  REGISTRATION_COURSE_V1_LIST,
  FORUM_V1_SELECT,
  POST_NOTAPPROVE_V1_SELECT,
  POST_NOTAPPROVE_V1_SELECT_MORE,
  POST_APPROVE_V1_SELECT,
  POST_APPROVE_V1_SELECT_MORE,
  POST_NOTVISIBLE_V1_SELECT,
  POST_NOTVISIBLE_V1_SELECT_MORE,
  POST_V1_SELECT_FILTER,
  POST_V1_SELECT_MORE_FILTER,
  POST_V1_SELECT_EMPTY,
  /*--------------POST FORUM-----------------*/

  POST_V1_SELECT,
  COMMENTS_V1_SELECT,
  COMMENTS_V1_EMPTY,
  POST_V1_INFORMATIN,
  POST_V1_INFORMATIN_EMPTY,
  /*------------------------------------------------- */
  STCOK_V1_SELECT,
  STCOK_V1_SELECT_EMPTY,
  PROFILE_V1_SELECT,
  PROFILE_V1_SELECT_EMPTY,
  ORDERS_V1_SELECT,
  ORDERS_V1_SELECT_AGGREGATES,
  ORDERS_V1_SELECT_MORE,
  PROFILE_V1_EMPTY,
  PROFILE_V1_SELECT_ORDER,
  PERSON_V1_SELECT_INTEGRATE_PROFILES,
  PERSON_V1_SELECT_INTEGRATE_PROFILES_EMPTY,
  STOCK_V1_SELECT_SUMMARIES,
  STOCK_V1_SELECT_SEARCHSYMBOL,
  STOCK_V1_SELECT_SUMMARIES_MORE,
  STOCK_V1_SELECT_SUMMARIES_PAGE_STOCK_EMPTY,
  STOCK_V1_SELECT_SUMMARIES_PAGE_STOCK,
  STOCK_V1_MANAGEMENT_DATA_SELECT,
  SECTOR_V1_MANAGEMENT_DATA_SELECT,
  CREADIT_PROFILE_V1_SELECT,
  CREADIT_PROFILE_V1_EMPTY,
  PROFILE_V1_SELECT_INTRODUCING,
  COURSES_V1_SELECT,
  COURSES_V1_EMPTY,
  COURSES_V1_INSERT,
  BONUS_V1_SELECT,
  BONUS_V1_SELECT_REQUESTS,
  BONUS_V1_SELECT_EXCEL,
  BONUS_V1_SELECT_EXCEL_REQUEST,
  BONUS_V1_SELECT_EXCEL_LOADING,
  BONUS_V1_SELECT_EXCEL_ISOK,
  BONUS_V1_SELECT_EXCEL_EMPTY,
  BONUS_V1_AGGREGATED,
  BONUS_V1_AGGREGATED_LOADING,
  BONUS_V1_SELECT_MANGEMENT,
  BONUS_V1_SELECT_MANGEMENT_LOADING,
  BONUS_V1_SELECT_CALCULATE_CONFIICT,
  BONUS_V1_SELECT_CALCULATE_CONFIICT_EMPTY,
  BONUS_V1_SELECT_SELECT_CONFIICT,
  BONUS_V1_SELECT_SELECT_CONFIICT_LOADING,
  GIFT_V1_SELECT_REGISTRATIONS,
  GIFT_V1_SELECT_REGISTRATIONS_RESULT_ACTION,
  GIFT_V1_SELECT_REGISTRATIONS_RESULT_ACTION_EMPTY,
  GIFT_V1_SELECT_REGISTRATIONS_EMPTY,
  GIFT_V1_SELECT_REGISTRATIONS_EXCEL,
  GIFT_V1_SELECT_REGISTRATIONS_EXCEL_LOADING,
  GIFT_V1_SELECT_REGISTRATIONS_MORE,
  GIFT_V1_SELECT_REGISTRATIONS_EXCEL_ISOK,
  GIFT_V1_SELECT_REGISTRATIONS_EXCEL_EMPTY,
  GIFT_V1_SELECT,
  GIFT_V1_SELECT_MORE,
  GIFT_V1_SELECT_ACTIVE_NAME,
  GIFT_V1_EMPTY,
  GIFT_V1_CATEGORIES,
  GIFT_V1_SUBCATEGORIES,
  GIFTCASH_V1_SELECT,
  SUBSCRIPTION_PLANS_V1_SELECT,
  SIGANL_V1_SELECT,
  SIGANL_V1_DOCUMENT_SELECT,
  SIGANL_V1_DOCUMENT_SELECT_EMPTY,
  SIGANL_V1_DOCUMENT_SELECT_LOADING,
  MEMBER_SUBSCRIPTION_V1_SELECT,
  GIFTAGGREGATED_V1_SELECT,
  GIFTAGGREGATED_V1_SELECT_FILTER,
  GIFTAGGREGATED_V1_EMPTY,
  GIFTAGGREGATED_V1_lOADING,
  GIFTCASHAGGREGATED_V1_SELECT,
  GIFTCASHAGGREGATED_V1_EMPTY,
  GIFTCASHAGGREGATED_V1_lOADING,
  GIFTCASHAGGREGATED_V1_SELECT_FILTER,
  DISCOUNT_CODE_SELECT,
  DISCOUNT_CODE_EXCEL_SELECT,
  DISCOUNT_CODE_EXCEL_EMPTY,
  STEPBYSTEP_DISCOUNT_SELECT,
  COMPETITIONS_V1_SELECT,
  COMPETITIONS_V1_SELECT_IN_RANGE,
  PERFORMANCE_SELECT_BY_ID,
  PARTICIPATIONS_V1_SELECT,
  PARTICIPATIONS_V1_EMPTY,
  PARTICIPATIONS_ById_V1_EMPTY,
  COMPETITIONS_PROFILE_V1_SELECT,
  COMPETITIONS_PROFILE_V1_EMPTY,
  NOTIFY_V1_SELECT,
  NOTIFY_V1_SELECT_MORE,
  NOTIFY_V1_SELECT_TOTAL,
  NOTIFY_V1_SELECT_NATION_ID,
  USERS_V1_SELECT,
  LOG_IN_LIST_SELECT,
  CUSTOMERS_V1_SELECT,
  CUSTOMERS_V1_SELECT_LOADING,
  CUSTOMER_V1_SELECT_EMPTY,
  CUSTOMER_V1_SELECT_ATTACHMENTS,
  SELECT_STOCK_DETAILS,
  SELECT_STOCK_DETAILS_EMPTY,
  CHANGE_BROKER_SELECT,
  CHANGE_BROKER_SELECT_IMG,
  CHANGE_BROKER_SELECT_EMPTY,
  SELECT_USER_STATUS,
  SELECT_USER_STATUS_EMPTY,
  PRTFOLIO_REMAIN,
  PRTFOLIO_REMAIN_EMPTY,
  SELECT_INTRODUCTION_DETAIL,
  SELECT_INTRODUCTION_DETAIL_EMPTY,
  UPDATE_CHANGE_INTRODUCER,
  UPDATE_DELETE_INTRODUCER,
  GET_KYC_PROFILE_SELECT,
  GET_KYC_PROFILE_REMOVE,
  SELECT_CLUBMEMBER_COUNT,
  SELECT_TOTAL_BONUS,
  SELECT_CLUBMEMBER_REGISTRATION_COUNT,
  SELECT_CLUBMEMBER_DAILY_LOGIN_LOG,
  SELECT_CLUBMEMBER_BY_BOURSE_CODE_COUNT,
  MARKETER_V1_SELECT_LOADING,
  MARKETER_V1_SELECT,
  MARKETER_SELECT_ATTACHMENTS,
  MARKETER_SELECT_ATTACHMENTS_EMPTY,
  WORK_WITH_US_V1_SELECT,
  WORK_WITH_US_V1_SELECT_LOADING,
  WORK_WITH_US_V1_SELECT_ATTACHMENTS,
  WORK_WITH_US_V1_SELECT_ATTACHMENTS_EMPTY,
  WORK_WITH_US_V1_UPDATE,
  CONTACT_US_V1_SELECT,
  CONTACT_US_V1_SELECT_LOADING,
  CONTACT_US_V1_SELECT_DETAILS,
  CONTACT_US_V1_SELECT_DETAILS_EMPTY,
  BONUS_V1_SELECT_CALCULATE_CONFIICT_LOADING,
  PAYMENTS_V1_SELECT,
  PAYMENTS_V1_SELECT_LOADING,
  STOCK_CASH_SELECT,
  STOCK_CASH_SELECT_LOADING,
};
